### findAll
GET http://localhost:3000/api/vuelos

### findOne
GET http://localhost:3000/api/vuelos/1

### add
POST http://localhost:3000/api/vuelos
Content-Type: application/json

{
    "codigo": "2",
    "aerolinea": "Qatar Airways",
    "estado": "Pendiente",
    "duracion": "10 horas",
    "cupo": 150,
    "disponibilidad": true
}

### update PUT
PUT http://localhost:3000/api/vuelos/2
Content-Type: application/json

{
    "codigo": "2",
    "aerolinea": "Qatar Airways",
    "estado": "Pendiente",
    "duracion": "24 horas",
    "cupo": 150,
    "disponibilidad": true
}

### update PATCH
PATCH http://localhost:3000/api/vuelos/2
Content-Type: application/json

{
    "duracion": "10 horas"
}

### delete
DELETE http://localhost:3000/api/vuelos/2